# .readthedocs.yaml
version: 2

# Build tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - doxygen

  # Pre-build commands
  commands:
    - pwd
    - ls -la
    - cd docs
    - doxygen DoxyFile

# Build documentation in the docs/sphinx directory
sphinx:
  configuration: docs/sphinx/conf.py

# Python dependencies
python:
  install:
    - requirements: docs/sphinx/requirements.txt



        
