version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/sphinx/conf.py

# Python dependencies
python:
  install:
    - requirements: docs/sphinx/requirements.txt

# Environment setup (install doxygen if not available)
build:
  apt_packages:
    - doxygen
  commands:
    - cd docs && doxygen DoxyFile

        
